# Generated by Django 4.0.2 on 2022-02-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='core/avatar/blank_profile.png', upload_to='core/avatar'),
        ),
    ]
