# Generated by Django 4.0.2 on 2022-02-12 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_alter_project_assign_alter_task_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign',
            field=models.ManyToManyField(related_name='task_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_project_assign', to='projects.project'),
        ),
    ]
