# Generated by Django 4.0.2 on 2022-02-19 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_alter_task_assign_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
